[project]
name = "taskr"
version = "0.1"
description = "simple todo app"
dependencies = [
    "flask",
]
requires-python = ">=3.14"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"